/**
 * Bundles the gateway into a single Deno-loadable module.
 *
 * Why bundle rather than let Deno resolve the imports: the handler imports the app's own
 * `lib/ai/*` modules with extensionless specifiers, which is correct for Next.js and
 * invalid for Deno. Rewriting every import to carry `.ts` would break the app build.
 * Bundling keeps one source of truth — the same policy and tool code the browser and the
 * Worker use — and hands Deno a file it can load without any resolution rules at all.
 *
 *   node gateway/build-deno.mjs
 */
import { build } from "esbuild";

await build({
  entryPoints: ["gateway/src/index.ts"],
  outfile: "gateway/deno/gateway.bundle.js",
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  banner: { js: "// GENERATED by gateway/build-deno.mjs — edit gateway/src/index.ts instead.\n" },
});

console.log("gateway/deno/gateway.bundle.js written");
