/**
 * Bundles the gateway into a single module each non-Cloudflare host can load.
 *
 * Why bundle rather than let each runtime resolve the imports: the handler imports the
 * app's `lib/ai/*` modules with extensionless specifiers, which is correct for Next.js,
 * invalid for Deno, and outside the project root for a standalone Vercel or Function
 * Compute deployment. Rewriting every import would break the app build. Bundling keeps
 * one source of truth — the same policy and tool code the browser and the Worker use —
 * and hands each host a file it can load with no resolution rules at all.
 *
 *   npm run build:gateway
 */
import { build } from "esbuild";

const targets = [
  "gateway/deno/gateway.bundle.js",
  "gateway/vercel/gateway.bundle.js",
  "gateway/aliyun/gateway.bundle.js",
];

for (const outfile of targets) {
  await build({
    entryPoints: ["gateway/src/index.ts"],
    outfile,
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    banner: { js: "// GENERATED by gateway/build-gateway.mjs — edit gateway/src/index.ts instead.\n" },
  });
  console.log(outfile);
}
