/**
 * Bundles the gateway for each non-Cloudflare host.
 *
 * Why bundle rather than let each runtime resolve the imports: the handler imports the
 * app's `lib/ai/*` modules with extensionless specifiers, which is correct for Next.js,
 * invalid for Deno, and outside the project root for a standalone Vercel or Function
 * Compute deployment. Rewriting every import would break the app build. Bundling keeps one
 * source of truth — the same policy and tool code the browser and the Worker use — and
 * hands each host a file it can load with no resolution rules at all.
 *
 * Vercel gets the adapter bundled in too, so `api/gateway.mjs` is one self-contained
 * function file. A serverless builder has opinions about extensions, `type: module` and
 * sibling imports; none of them can go wrong if there is nothing left to resolve.
 *
 *   npm run build:gateway
 */
import { build } from "esbuild";

const banner = { js: "// GENERATED by gateway/build-gateway.mjs — edit the source, never this file.\n" };
const common = { bundle: true, format: "esm", target: "es2022", banner };

// Handler only: these hosts have their own adapter file alongside.
for (const outfile of ["gateway/deno/gateway.bundle.js", "gateway/aliyun/gateway.bundle.js"]) {
  await build({ ...common, entryPoints: ["gateway/src/index.ts"], outfile, platform: "neutral" });
  console.log(outfile);
}

// Vercel: adapter + handler in one file, with Node built-ins left external.
await build({
  ...common,
  entryPoints: ["gateway/vercel/src/adapter.ts"],
  outfile: "gateway/vercel/api/gateway.mjs",
  platform: "node",
  external: ["node:*"],
});
console.log("gateway/vercel/api/gateway.mjs");
